### ISSUE TITLE
Don't enable Zero Spam Enhanced Protection during default configuration

### ISSUE THREAD

**Issue by ethanclevenger91** [Highfivery/wordpress-zero-spam#296] opened 2021-12-29 00:00 UTC
**Is your feature request related to a problem? Please describe.**
The "Zero Spam Enhanced Protection" setting requires further configuration (a license key) and therefore doesn’t seem like a sensible default to enable. Many users likely won’t even want to purchase a key and will visit the settings after running the wizard to disable it anyway, which defeats the purpose of the one-click automated wizard.

**Describe the solution you'd like**
Don't enable Zero Spam Enhanced Protection by default.

**Describe alternatives you've considered**
Manually turning this setting off on every site I install this plugin on and use the default settings.

**Comment by bmarshall511** [comment] 2022-01-03 13:32
@ethanclevenger91 closing, works as intended. The Zero Spam service helps pay for the continued development of the plugin and is recommended to provide enhanced protection of the site. If it's unneeded, you're able to disable it via admin or if need to do it in bulk, you can use the WP CLI commands.

**Closed by bmarshall511** 2022-01-03 13:32 UTC
Labels: feature request
